-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 14:28:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaDeVentas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaDeVentas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaDeVentas` DEFAULT CHARACTER SET utf8 ;
USE `SistemaDeVentas` ;

-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Puesto_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Puesto_Empleado` (
  `Pk_Id_Puesto` INT NOT NULL AUTO_INCREMENT,
  `cNombre_Puesto` VARCHAR(45) NULL,
  PRIMARY KEY (`Pk_Id_Puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Estado_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Estado_Empleado` (
  `Pk_Id_Estado` INT NOT NULL AUTO_INCREMENT,
  `cNombre_Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`Pk_Id_Estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Empleado` (
  `Pk_Id_Empleado` INT NOT NULL AUTO_INCREMENT,
  `cNombre_Empleado` VARCHAR(45) NULL,
  `cApellido_Empleado` VARCHAR(45) NULL,
  `Fk_Id_Puesto` INT NOT NULL,
  `Fk_Id_Estado` INT NOT NULL,
  PRIMARY KEY (`Pk_Id_Empleado`),
  INDEX `fk_Tbl_Empleado_Tbl_Puesto_Empleado_idx` (`Fk_Id_Puesto` ASC) ,
  INDEX `fk_Tbl_Empleado_Tbl_Estado_Empleado1_idx` (`Fk_Id_Estado` ASC) ,
  CONSTRAINT `fk_Tbl_Empleado_Tbl_Puesto_Empleado`
    FOREIGN KEY (`Fk_Id_Puesto`)
    REFERENCES `SistemaDeVentas`.`Tbl_Puesto_Empleado` (`Pk_Id_Puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Empleado_Tbl_Estado_Empleado1`
    FOREIGN KEY (`Fk_Id_Estado`)
    REFERENCES `SistemaDeVentas`.`Tbl_Estado_Empleado` (`Pk_Id_Estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Producto` (
  `Pk_Id_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(115) NULL,
  `Precio` FLOAT NULL,
  PRIMARY KEY (`Pk_Id_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Bodega` (
  `Pk_Id_Bodega` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Bodega` VARCHAR(45) NULL,
  `Existencia` INT NULL,
  `Fk_Id_Producto` INT NOT NULL,
  `Fk_Id_Empleado` INT NOT NULL,
  PRIMARY KEY (`Pk_Id_Bodega`),
  INDEX `fk_Tbl_Bodega_Tbl_Producto1_idx` (`Fk_Id_Producto` ASC) ,
  INDEX `fk_Tbl_Bodega_Tbl_Empleado1_idx` (`Fk_Id_Empleado` ASC) ,
  CONSTRAINT `fk_Tbl_Bodega_Tbl_Producto1`
    FOREIGN KEY (`Fk_Id_Producto`)
    REFERENCES `SistemaDeVentas`.`Tbl_Producto` (`Pk_Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Bodega_Tbl_Empleado1`
    FOREIGN KEY (`Fk_Id_Empleado`)
    REFERENCES `SistemaDeVentas`.`Tbl_Empleado` (`Pk_Id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Tipo_De_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Tipo_De_Pago` (
  `Pk_Id_Pago` INT NOT NULL,
  `cNombre_Tipo_Pago` VARCHAR(45) NULL,
  PRIMARY KEY (`Pk_Id_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Cliente` (
  `Pk_Id_Cliente` INT NOT NULL,
  `cNombre_Cliente` VARCHAR(45) NULL,
  `cApellido_Cliente` VARCHAR(45) NULL,
  `cNit_Cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`Pk_Id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Pk_Tbl_Aprobacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Pk_Tbl_Aprobacion` (
  `Pk_Id_Aprobacion` INT NOT NULL AUTO_INCREMENT,
  `cNombre_Aprobacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Pk_Id_Aprobacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Factura` (
  `Pk_Id_Factura` INT NOT NULL AUTO_INCREMENT,
  `cFecha_Emision` DATE NULL,
  `Fk_Id_Pago` INT NOT NULL,
  `Fk_Id_Empleado` INT NOT NULL,
  `Fk_Id_Producto` INT NOT NULL,
  `Fk_Id_Cliente` INT NOT NULL,
  `Fk_Id_Aprobacion` INT NOT NULL,
  PRIMARY KEY (`Pk_Id_Factura`),
  INDEX `fk_Tbl_Factura_Tbl_Tipo_De_Pago1_idx` (`Fk_Id_Pago` ASC) ,
  INDEX `fk_Tbl_Factura_Tbl_Empleado1_idx` (`Fk_Id_Empleado` ASC) ,
  INDEX `fk_Tbl_Factura_Tbl_Producto1_idx` (`Fk_Id_Producto` ASC) ,
  INDEX `fk_Tbl_Factura_Tbl_Cliente1_idx` (`Fk_Id_Cliente` ASC) ,
  INDEX `fk_Tbl_Factura_Pk_Tbl_Aprobacion1_idx` (`Fk_Id_Aprobacion` ASC) ,
  CONSTRAINT `fk_Tbl_Factura_Tbl_Tipo_De_Pago1`
    FOREIGN KEY (`Fk_Id_Pago`)
    REFERENCES `SistemaDeVentas`.`Tbl_Tipo_De_Pago` (`Pk_Id_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Factura_Tbl_Empleado1`
    FOREIGN KEY (`Fk_Id_Empleado`)
    REFERENCES `SistemaDeVentas`.`Tbl_Empleado` (`Pk_Id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Factura_Tbl_Producto1`
    FOREIGN KEY (`Fk_Id_Producto`)
    REFERENCES `SistemaDeVentas`.`Tbl_Producto` (`Pk_Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Factura_Tbl_Cliente1`
    FOREIGN KEY (`Fk_Id_Cliente`)
    REFERENCES `SistemaDeVentas`.`Tbl_Cliente` (`Pk_Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Factura_Pk_Tbl_Aprobacion1`
    FOREIGN KEY (`Fk_Id_Aprobacion`)
    REFERENCES `SistemaDeVentas`.`Pk_Tbl_Aprobacion` (`Pk_Id_Aprobacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Cotización`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Cotización` (
  `Pk_Id_Cotizacion` INT NOT NULL AUTO_INCREMENT,
  `cNombre_Cotizacion` VARCHAR(45) NULL,
  `cFecha_Cotizacion` VARCHAR(45) NULL,
  `Fk_Id_Producto` INT NOT NULL,
  `Fk_Id_Cliente` INT NOT NULL,
  PRIMARY KEY (`Pk_Id_Cotizacion`),
  INDEX `fk_Tbl_Cotización_Tbl_Producto1_idx` (`Fk_Id_Producto` ASC) ,
  INDEX `fk_Tbl_Cotización_Tbl_Cliente1_idx` (`Fk_Id_Cliente` ASC) ,
  CONSTRAINT `fk_Tbl_Cotización_Tbl_Producto1`
    FOREIGN KEY (`Fk_Id_Producto`)
    REFERENCES `SistemaDeVentas`.`Tbl_Producto` (`Pk_Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Cotización_Tbl_Cliente1`
    FOREIGN KEY (`Fk_Id_Cliente`)
    REFERENCES `SistemaDeVentas`.`Tbl_Cliente` (`Pk_Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Call_Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Call_Center` (
  `Pk_Id_Call_Center` INT NOT NULL AUTO_INCREMENT,
  `cNombre_Call_Center` VARCHAR(45) NULL,
  `Fk_Id_Empleado` INT NOT NULL,
  PRIMARY KEY (`Pk_Id_Call_Center`),
  INDEX `fk_Tbl_Call_Center_Tbl_Empleado1_idx` (`Fk_Id_Empleado` ASC) ,
  CONSTRAINT `fk_Tbl_Call_Center_Tbl_Empleado1`
    FOREIGN KEY (`Fk_Id_Empleado`)
    REFERENCES `SistemaDeVentas`.`Tbl_Empleado` (`Pk_Id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Id_Destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Id_Destino` (
  `Id_Destino` INT NOT NULL AUTO_INCREMENT,
  `Numero_De_Zona` VARCHAR(2) NULL,
  PRIMARY KEY (`Id_Destino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Ruta` (
  `Pk_Id_Ruta` INT NOT NULL,
  `Nombre_Ruta_O_Direccion` VARCHAR(45) NULL,
  `Tbl_Cliente_Pk_Id_Cliente` INT NOT NULL,
  `Tbl_Empleado_Pk_Id_Empleado` INT NOT NULL,
  `Id_Destino_Id_Destino` INT NOT NULL,
  PRIMARY KEY (`Pk_Id_Ruta`),
  INDEX `fk_Tbl_Ruta_Tbl_Cliente1_idx` (`Tbl_Cliente_Pk_Id_Cliente` ASC) ,
  INDEX `fk_Tbl_Ruta_Tbl_Empleado1_idx` (`Tbl_Empleado_Pk_Id_Empleado` ASC) ,
  INDEX `fk_Tbl_Ruta_Id_Destino1_idx` (`Id_Destino_Id_Destino` ASC) ,
  CONSTRAINT `fk_Tbl_Ruta_Tbl_Cliente1`
    FOREIGN KEY (`Tbl_Cliente_Pk_Id_Cliente`)
    REFERENCES `SistemaDeVentas`.`Tbl_Cliente` (`Pk_Id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Ruta_Tbl_Empleado1`
    FOREIGN KEY (`Tbl_Empleado_Pk_Id_Empleado`)
    REFERENCES `SistemaDeVentas`.`Tbl_Empleado` (`Pk_Id_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Ruta_Id_Destino1`
    FOREIGN KEY (`Id_Destino_Id_Destino`)
    REFERENCES `SistemaDeVentas`.`Id_Destino` (`Id_Destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaDeVentas`.`Tbl_Orden_De_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaDeVentas`.`Tbl_Orden_De_Producto` (
  `Pk_Id_Orden_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_De_Orden` VARCHAR(45) NULL,
  `Fk_Id_Bodega` INT NOT NULL,
  `Fk_Id_Producto` INT NOT NULL,
  PRIMARY KEY (`Pk_Id_Orden_Producto`),
  INDEX `fk_Tbl_Orden_De_Producto_Tbl_Bodega1_idx` (`Fk_Id_Bodega` ASC) ,
  INDEX `fk_Tbl_Orden_De_Producto_Tbl_Producto1_idx` (`Fk_Id_Producto` ASC) ,
  CONSTRAINT `fk_Tbl_Orden_De_Producto_Tbl_Bodega1`
    FOREIGN KEY (`Fk_Id_Bodega`)
    REFERENCES `SistemaDeVentas`.`Tbl_Bodega` (`Pk_Id_Bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tbl_Orden_De_Producto_Tbl_Producto1`
    FOREIGN KEY (`Fk_Id_Producto`)
    REFERENCES `SistemaDeVentas`.`Tbl_Producto` (`Pk_Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
